language: node_js
node_js:
  - 10
before_install:
  - npm i -g npm@6.9.0
deploy:
  provider: heroku
  api_key:
    secure: bMvUZdSQhA/2Km8moUEz0IIIAxqb0PvMrm/dcwi1S1Z6aqgJ+TdX+69Mt4vEJrC1nk/UJUAuMS1rYdOHTfllrWhBpIfNZ2Bxv0uywzZcqzH1dbuuatNqhT7n2Cu4hDzS4IP+vrkQtNRsuYcsYAlNNJH1wPFHmW1jssXdmtwiGGD8zJtxSGLvWP0tJSXiKEnAq22X9NilcwY/eKHUFEFfOGmRRMfFkV9ZvZFKwWw9aFGdJSwVGn4qcN8IPKnFDL+0oYHWZt6af8MMocdHX7S1LrJs05Qc95Q56XE0N/cZrO3n0RYICxZdbpnWoVtGIGd2x0wcNa1GdEOUbZML4SLDjBWwizO1qCSgA3b5dFhpZ0b+b3yWulHYWAxtOv2ZraLXSXkmp2FzGiGicNs5hRK4fSr4rOZ5+8ZQKBRs2O2kypJ39kS6TRRaMnHPY0JhhoWwZTrBSXzT9vN2xtZmX+i+Q9MuKizCxtqgXh7kEhni+UfjXpppc4mw3Tb8mR1v2ib8aEQtAYucj0iql2+3DotELHo2OxKVis1OapoTjXxSs8tbycfd4oOWjD574On5lIvQK1KI63QIcgVWZTFNMwqzPekq7lVZ7MWCGmQS4G46wg5np5uKcFMK8uJu6hFjWexHwzcERlxRvZnPPG0zn2JaBwcfafu5L9HYSMAbEfdMN1E=
  app: naccc
  on:
    repo: sofiacf/naccc
