language: java
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
deploy:
  provider: heroku
  api_key:
    secure: GVnULnvpBBwZE0S+8UuIBX6lonFA9YM0IGXK9vlcrhgr+4Qngkd/1Yxf35K6ttt6LB8SkpMXVPo4+IEwQV6FDb5DT/kty/r32vc8Iqj2Bp+nPyc1qr9QsJzBqnZ59DU9cCGdxk/+oXGHCMVZq6xu8F9bCJTQblsNquNtYUIYi6ceSKqPJPIObA5gWv9AOJHDZoLvKYWLxksTQnQMwfF7PPnOR2cXav9irgehM22oUnx7U1FOM5jklDJ7mtJtdowYeT8IlnKzLS5HK0I55PC+WMGDy/1pl54ikZX4pMKQOPTAQAznWvnZBcGO7Y5ibWgGJf2lfUZnfaoCOgKacj3zi+7X18Ye9ic5qYgNqCylHs11+HHTpAYuIsrt8aZIUKC5zLfy68gqZEXty+obLpEsC/gpVEz27axuiuR/RbL3xHy8Yzhv6rRdtQ4zmkrNKIX5kJAMG8tfjUEBbLeg7GMcjqf+xgQlfWXYvtoN1BSTznKnfRcrkAw7I2oK+uJpznZfHEPOJTbiHiFDbnW0ovK0FtGR0hIBZHZ31HITBWKkuRK6pjfWSDJbzlOX1Tp/HrteXKrvdV8PecnRBYbDkPGr5+rhr59fSa5mNWy+HHI9L29heq64UwK0mqy//mTTE+f0wVCLfW9IMgKpA/UALZBNxUS+Q5wYRTbYSKVDrajP6d4=
  app: naccc
  on:
    repo: sofiacf/naccc
